/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import entidades.Usuario;

/**
 *
 * @author matheus.kunz
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        dskPainel = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        mnBarra = new javax.swing.JMenuBar();
        mnCadastros = new javax.swing.JMenu();
        mnClientes = new javax.swing.JMenuItem();
        mnFuncionarios = new javax.swing.JMenuItem();
        mnProdutos = new javax.swing.JMenuItem();
        mnUsuarios = new javax.swing.JMenuItem();
        mnRelatorios = new javax.swing.JMenu();
        mnRelClientes = new javax.swing.JMenuItem();
        mnRelFuncionarios = new javax.swing.JMenuItem();
        mnRelProdutos = new javax.swing.JMenuItem();
        mnAgendas = new javax.swing.JMenu();
        mnAgendamento = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/istockphoto-1446474893-612x612.jpg"))); // NOI18N

        dskPainel.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dskPainelLayout = new javax.swing.GroupLayout(dskPainel);
        dskPainel.setLayout(dskPainelLayout);
        dskPainelLayout.setHorizontalGroup(
            dskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskPainelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dskPainelLayout.setVerticalGroup(
            dskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskPainelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mnCadastros.setText("Cadastros");
        mnCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrosActionPerformed(evt);
            }
        });

        mnClientes.setText("Clientes");
        mnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClientesActionPerformed(evt);
            }
        });
        mnCadastros.add(mnClientes);

        mnFuncionarios.setText("Funcionários");
        mnFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFuncionariosActionPerformed(evt);
            }
        });
        mnCadastros.add(mnFuncionarios);

        mnProdutos.setText("Produtos");
        mnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProdutosActionPerformed(evt);
            }
        });
        mnCadastros.add(mnProdutos);

        mnUsuarios.setText("Usuarios");
        mnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUsuariosActionPerformed(evt);
            }
        });
        mnCadastros.add(mnUsuarios);

        mnBarra.add(mnCadastros);

        mnRelatorios.setText("Relatórios");

        mnRelClientes.setText("Clientes");
        mnRelClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelClientesActionPerformed(evt);
            }
        });
        mnRelatorios.add(mnRelClientes);

        mnRelFuncionarios.setText("Funcionários");
        mnRelFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelFuncionariosActionPerformed(evt);
            }
        });
        mnRelatorios.add(mnRelFuncionarios);

        mnRelProdutos.setText("Produtos");
        mnRelProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelProdutosActionPerformed(evt);
            }
        });
        mnRelatorios.add(mnRelProdutos);

        mnBarra.add(mnRelatorios);

        mnAgendas.setText("Agendas");

        mnAgendamento.setText("Agendamento");
        mnAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAgendamentoActionPerformed(evt);
            }
        });
        mnAgendas.add(mnAgendamento);

        mnBarra.add(mnAgendas);

        setJMenuBar(mnBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dskPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dskPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Inicia tela cliente
    private void mnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClientesActionPerformed
        TelaCliente tc = new TelaCliente();
        dskPainel.add(tc);
        tc.setVisible(true);
    }//GEN-LAST:event_mnClientesActionPerformed

//Inicia tela funcionario
    private void mnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFuncionariosActionPerformed
        TelaFuncionario tf = new TelaFuncionario();
        dskPainel.add(tf);
        tf.setVisible(true);
    }//GEN-LAST:event_mnFuncionariosActionPerformed

//Inicia tela produto
    private void mnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProdutosActionPerformed
        TelaProduto tp = new TelaProduto();
        dskPainel.add(tp);
        tp.setVisible(true);
    }//GEN-LAST:event_mnProdutosActionPerformed

    private void mnCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnCadastrosActionPerformed

    private void mnRelClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelClientesActionPerformed
        TelaPDFClientes tpc = new TelaPDFClientes();
        dskPainel.add(tpc);
        tpc.setVisible(true);
    }//GEN-LAST:event_mnRelClientesActionPerformed

    private void mnRelFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelFuncionariosActionPerformed
        TelaPDFFuncionarios tpf = new TelaPDFFuncionarios();
        dskPainel.add(tpf);
        tpf.setVisible(true);
    }//GEN-LAST:event_mnRelFuncionariosActionPerformed

    private void mnRelProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelProdutosActionPerformed
        TelaPDFProdutos tpp = new TelaPDFProdutos();
        dskPainel.add(tpp);
        tpp.setVisible(true);
    }//GEN-LAST:event_mnRelProdutosActionPerformed

    private void mnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsuariosActionPerformed
        TelaUsuario tu = new TelaUsuario();
        dskPainel.add(tu);
        tu.setVisible(true);
    }//GEN-LAST:event_mnUsuariosActionPerformed

    private void mnAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAgendamentoActionPerformed
        TelaAgendamento ta = new TelaAgendamento();
        dskPainel.add(ta);
        ta.setVisible(true);
    }//GEN-LAST:event_mnAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

//Inicia a tela principal
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPainel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnAgendamento;
    private javax.swing.JMenu mnAgendas;
    private javax.swing.JMenuBar mnBarra;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenuItem mnClientes;
    private javax.swing.JMenuItem mnFuncionarios;
    private javax.swing.JMenuItem mnProdutos;
    private javax.swing.JMenuItem mnRelClientes;
    private javax.swing.JMenuItem mnRelFuncionarios;
    private javax.swing.JMenuItem mnRelProdutos;
    private javax.swing.JMenu mnRelatorios;
    private javax.swing.JMenuItem mnUsuarios;
    // End of variables declaration//GEN-END:variables
}
