/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author matheus.kunz
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPainel = new javax.swing.JDesktopPane();
        mnBarra = new javax.swing.JMenuBar();
        mnCadastros = new javax.swing.JMenu();
        mnClientes = new javax.swing.JMenuItem();
        mnFuncionarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskPainelLayout = new javax.swing.GroupLayout(dskPainel);
        dskPainel.setLayout(dskPainelLayout);
        dskPainelLayout.setHorizontalGroup(
            dskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dskPainelLayout.setVerticalGroup(
            dskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        mnCadastros.setText("Cadastros");

        mnClientes.setText("Clientes");
        mnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClientesActionPerformed(evt);
            }
        });
        mnCadastros.add(mnClientes);

        mnFuncionarios.setText("Funcionários");
        mnFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFuncionariosActionPerformed(evt);
            }
        });
        mnCadastros.add(mnFuncionarios);

        mnBarra.add(mnCadastros);

        setJMenuBar(mnBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        //Inicia tela cliente
    private void mnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClientesActionPerformed
        TelaCliente tc = new TelaCliente();
        dskPainel.add(tc);
        tc.setVisible(true);
    }//GEN-LAST:event_mnClientesActionPerformed
        //Inicia tela funcionario
    private void mnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFuncionariosActionPerformed
        TelaFuncionario tf = new TelaFuncionario();
        dskPainel.add(tf);
        tf.setVisible(true);
    }//GEN-LAST:event_mnFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPainel;
    private javax.swing.JMenuBar mnBarra;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenuItem mnClientes;
    private javax.swing.JMenuItem mnFuncionarios;
    // End of variables declaration//GEN-END:variables
}
