/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import apoio.PDFManager;
import controladores.ControlaCliente;
import controladores.ControlaFuncionario;
import controladores.ControlaProduto;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author mateus
 */
public class TelaPDFProdutos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaPDF
     */
    public TelaPDFProdutos() {
        initComponents();
    }

    ControlaCliente cc = new ControlaCliente();
    ControlaFuncionario cf = new ControlaFuncionario();
    ControlaProduto cp = new ControlaProduto();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCaminho = new javax.swing.JTextField();
        btnCaminho = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();

        setClosable(true);

        btnCaminho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ramificacao-do-codigo.png"))); // NOI18N
        btnCaminho.setText("Selecionar caminho");
        btnCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaminhoActionPerformed(evt);
            }
        });

        btnPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arquivo-pdf.png"))); // NOI18N
        btnPdf.setText("Gerar PDF");
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCaminho)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCaminho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(btnPdf)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaminho)
                    .addComponent(btnPdf))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaminhoActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Escolha um diretório");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);   // desativa "Todos os arquivos"

        int resultado = chooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File dir = chooser.getSelectedFile();
            txtCaminho.setText(dir.getAbsolutePath() + "/produtos.pdf");
        }
    }//GEN-LAST:event_btnCaminhoActionPerformed

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
        String caminho = txtCaminho.getText();
        if (caminho.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um caminho antes de gerar o PDF");
        } else {
            try {
                String[] ordem = {
                    "id", "descricao", "preco", "tipo", "tempoEstimado", "estoque"
                };
                String[] rotulos = {
                    "ID", "Descrição", "Preço", "Tipo", "Tempo Estimado", "Estoque"
                };

                int[] larguras = {4, 11, 8, 8, 6, 8};

                PDFManager.gerar(cp.recuperarTodos(), caminho, ordem, larguras, rotulos);
                JOptionPane.showMessageDialog(null, "PDF gerado com sucesso com o nome produtos.pdf");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao gerar o PDF");
                System.err.println("Ocorreu um erro ao gerar o PDF: " + ex);
            }
        }
    }//GEN-LAST:event_btnPdfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaminho;
    private javax.swing.JButton btnPdf;
    private javax.swing.JTextField txtCaminho;
    // End of variables declaration//GEN-END:variables
}
